import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./_components/theme-provider";

import { config } from "@/lib/wagmi/config";
import RootProvider from "@/provider";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider initialState={initialState}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <main className="h-[calc(100vh-4rem)]">{children}</main>
          </ThemeProvider>
          <Toaster />
        </RootProvider>
      </body>
    </html>
  );
}
